# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x0fvacation.common\")\n\x05Money\x12\x10\n\x08\x63urrency\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\"d\n\x08Location\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\x12\x14\n\x0c\x61irport_code\x18\x03 \x01(\t\x12\x10\n\x08latitude\x18\x04 \x01(\x01\x12\x11\n\tlongitude\x18\x05 \x01(\x01\"1\n\tDateRange\x12\x12\n\nstart_date\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x02 \x01(\t\"1\n\tTimeRange\x12\x12\n\nstart_time\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\t\"r\n\x0f\x43omponentScores\x12\x13\n\x0bprice_score\x18\x01 \x01(\x01\x12\x15\n\rquality_score\x18\x02 \x01(\x01\x12\x19\n\x11\x63onvenience_score\x18\x03 \x01(\x01\x12\x18\n\x10preference_score\x18\x04 \x01(\x01*\xa1\x01\n\x0ePreferenceType\x12\x16\n\x12PREFERENCE_UNKNOWN\x10\x00\x12\n\n\x06LUXURY\x10\x01\x12\n\n\x06\x42UDGET\x10\x02\x12\x0c\n\x08ROMANTIC\x10\x03\x12\n\n\x06\x46\x41MILY\x10\x04\x12\r\n\tADVENTURE\x10\x05\x12\x0b\n\x07\x43ULTURE\x10\x06\x12\x08\n\x04\x46OOD\x10\x07\x12\n\n\x06NATURE\x10\x08\x12\t\n\x05\x42\x45\x41\x43H\x10\t\x12\x08\n\x04\x43ITY\x10\nb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PREFERENCETYPE._serialized_start=397
  _PREFERENCETYPE._serialized_end=558
  _MONEY._serialized_start=33
  _MONEY._serialized_end=74
  _LOCATION._serialized_start=76
  _LOCATION._serialized_end=176
  _DATERANGE._serialized_start=178
  _DATERANGE._serialized_end=227
  _TIMERANGE._serialized_start=229
  _TIMERANGE._serialized_end=278
  _COMPONENTSCORES._serialized_start=280
  _COMPONENTSCORES._serialized_end=394
# @@protoc_insertion_point(module_scope)
