import { SectionType, Trip } from "../../../../shared/types";

const mockData: Trip[] = [
  {
    vibe: "Classic Highlights Route",
    layout: {
      sections: [
        {
          type: SectionType.FLIGHT,
          data: {
            id: "a1a76107-79b3-5b3b-9b9b-f0826e9ac765",
            outbound: {
              origin: {
                city: "",
                country: "IL",
                airport_code: "TLV",
                latitude: 0,
                longitude: 0,
              },
              destination: {
                city: "",
                country: "IT",
                airport_code: "FCO",
                latitude: 0,
                longitude: 0,
              },
              departure_time: "2026-05-05T18:00:00",
              arrival_time: "2026-05-05T20:40:00",
              duration_minutes: 220,
              stops: 0,
              layovers: [],
              airline: "LY",
              flight_number: "LY383",
              aircraft: "738",
              cabin_class: "economy",
              amenities: {
                wifi: false,
                meal: true,
                entertainment: false,
                power_outlet: false,
                legroom_inches: 0,
              },
              luggage: {
                checked_bags: 0,
                checked_bag_weight_kg: 0,
                carry_on_bags: 1,
                carry_on_weight_kg: 0,
                carry_on_dimensions_cm: "",
              },
            },
            total_price: {
              currency: "EUR",
              amount: 284.68,
            },
            price_per_person: {
              currency: "EUR",
              amount: 142.34,
            },
            scores: {
              price_score: 0.806206922228441,
              quality_score: 0,
              convenience_score: 0,
              preference_score: 0.8091954206393627,
            },
            booking_url: "",
            provider: "LY",
            available: true,
          },
        },
        {
          type: SectionType.STAY,
          data: {
            hotel: {
              id: "ca399b48-ca7c-5b55-b58e-6e057dae1d2f",
              name: "Hotel Lord Byron",
              description:
                "Experience the elegance of Hotel Lord Byron, an Art Deco gem nestled in the heart of Rome, where sophistication meets comfort.Luxurious AccommodationsRelax in one of our 28 stylish guestrooms, featuring memory foam beds, premium bedding, and modern amenities such as LCD televisions and minibars. Each room is designed for your utmost comfort, with complimentary toiletries and high-speed wireless internet access.Gastronomic DelightsIndulge in culinary excellence at our on-site restaurant, Sapori d",
              location: {
                city: "Rome",
                country: "IT",
                airport_code: "",
                latitude: 41.919861,
                longitude: 12.481478,
              },
              distance_to_center_km: 2.5,
              image: "https://static.cupid.travel/hotels/ex_73af06d5_z.jpg",
              rating: 9,
              review_count: 132,
              rating_category: "Exceptional",
              price_per_night: {
                currency: "USD",
                amount: 514.97,
              },
              total_price: {
                currency: "USD",
                amount: 1029.94,
              },
              additional_fees: [
                {
                  name: "mandatory tax",
                  amount: {
                    currency: "USD",
                    amount: 41.02,
                  },
                  mandatory: true,
                },
              ],
              room: {
                type: "Superior Room",
                beds: 1,
                bed_type: "standard",
                max_occupancy: 2,
                size_sqm: 0,
                features: [],
              },
              amenities: [
                "Facility_1054",
                "Facility_1091",
                "Facility_2020",
                "Facility_2050",
                "Facility_2247",
                "Facility_2253",
                "Facility_2259",
                "Facility_2261",
                "Facility_2411",
                "Facility_107",
              ],
              category: "luxury",
              star_rating: 5,
              scores: {
                price_score: 0,
                quality_score: 0.9,
                convenience_score: 0.75,
                preference_score: 0.5,
              },
              booking_url: "https://booking.liteapi.travel/hotels/lp19be2",
              provider: "nuitee",
              available: true,
            },
            activities: [],
          },
        },
        {
          type: SectionType.STAY,
          data: {
            hotel: {
              id: "109a3010-9875-599c-8c45-68a84fdad6e2",
              name: "Italiana Hotels Florence",
              description:
                "Luxurious Stay at Italiana Hotels FlorenceElegant Rooms and Outdoor Pool: Italiana Hotels Florence, just 4 km from the city centre, offers elegantly furnished rooms with modern amenities. Relax by the outdoor swimming pool or enjoy a meal at the gourmet restaurant overlooking the pool from the furnished terrace.Gourmet Dining Experience: Indulge in typical Tuscan and Mediterranean cuisine at the on-site restaurant open for dinner. In the summer, savor your meal al fresco on the terrace. Wake up ",
              location: {
                city: "Florence",
                country: "it",
                airport_code: "",
                latitude: 43.757526,
                longitude: 11.298492,
              },
              distance_to_center_km: 2.5,
              image: "https://static.cupid.travel/hotels/154104214.jpg",
              rating: 7.4,
              review_count: 1564,
              rating_category: "Very Good",
              price_per_night: {
                currency: "USD",
                amount: 158,
              },
              total_price: {
                currency: "USD",
                amount: 316,
              },
              additional_fees: [
                {
                  name: "City Tax",
                  amount: {
                    currency: "USD",
                    amount: 23.08,
                  },
                  mandatory: true,
                },
              ],
              room: {
                type: "Classic Twin Room",
                beds: 1,
                bed_type: "standard",
                max_occupancy: 2,
                size_sqm: 0,
                features: [],
              },
              amenities: [
                "Facility_2083",
                "Facility_2413",
                "Facility_16",
                "Facility_109",
                "Facility_301",
                "Facility_3",
                "Facility_5",
                "Facility_28",
                "Facility_4",
                "Facility_48",
              ],
              category: "upscale",
              star_rating: 4,
              scores: {
                price_score: 0.76,
                quality_score: 0.74,
                convenience_score: 0.75,
                preference_score: 0.5,
              },
              booking_url: "https://booking.liteapi.travel/hotels/lp1a731",
              provider: "nuitee",
              available: true,
            },
            activities: [
              {
                id: "duomo-climb-tour-001",
                name: "Duomo Complex Guided Tour with Dome Climb",
                description:
                  "Explore the iconic Duomo complex including Cathedral of Santa Maria del Fiore, climb Brunelleschi’s Dome (463 steps), visit Museo dell’Opera del Duomo, and Baptistery for panoramic views and Renaissance history.",
                category: 1,
                location: {
                  city: "Florence",
                  country: "IT",
                  airport_code: "FLR",
                  latitude: 43.7732,
                  longitude: 11.256,
                },
                distance_from_query_km: 0.1,
                rating: 4.8,
                review_count: 2450,
                price_per_person: {
                  currency: "EUR",
                  amount: 35,
                },
                price_details: {
                  adult_price: {
                    currency: "EUR",
                    amount: 35,
                  },
                  child_price: {
                    currency: "EUR",
                    amount: 25,
                  },
                  senior_price: {
                    currency: "EUR",
                    amount: 30,
                  },
                },
                duration_minutes: 180,
                available_times: [
                  {
                    date: "2026-05-07",
                    time: "08:30",
                    available_spots: 15,
                  },
                  {
                    date: "2026-05-08",
                    time: "08:30",
                    available_spots: 12,
                  },
                  {
                    date: "2026-05-09",
                    time: "08:30",
                    available_spots: 18,
                  },
                ],
                highlights: [
                  "Climb Brunelleschi’s Dome for stunning city views",
                  "Guided insights into Renaissance architecture",
                  "Skip-the-line access to key sites",
                ],
                included: [
                  "Expert English-speaking guide",
                  "Skip-the-line tickets",
                  "Headsets for larger groups",
                ],
                excluded: ["Meals", "Hotel pickup", "Personal expenses"],
                min_participants: 1,
                max_participants: 20,
                difficulty_level: "moderate",
                hotel_pickup: false,
                meal_included: false,
                cancellation_policy: "Free cancellation up to 24 hours before",
                scores: {
                  price_score: 0.9,
                  quality_score: 0.95,
                  convenience_score: 0.85,
                  preference_score: 1,
                },
                booking_url: "https://example.com/book/duomo-001",
                provider: "Florence Tours",
                available: true,
                image_urls: [
                  "https://example.com/images/duomo1.jpg",
                  "https://example.com/images/duomo2.jpg",
                ],
              },
              {
                id: "uffizi-express-002",
                name: "Skip-the-Line Uffizi Gallery Guided Tour",
                description:
                  "Discover Renaissance masterpieces at the Uffizi Gallery including Botticelli’s Birth of Venus, Leonardo da Vinci works, and Michelangelo, with expert commentary on Florence's art history.",
                category: 2,
                location: {
                  city: "Florence",
                  country: "IT",
                  airport_code: "FLR",
                  latitude: 43.7681,
                  longitude: 11.2558,
                },
                distance_from_query_km: 0.2,
                rating: 4.7,
                review_count: 3800,
                price_per_person: {
                  currency: "EUR",
                  amount: 55,
                },
                price_details: {
                  adult_price: {
                    currency: "EUR",
                    amount: 55,
                  },
                  child_price: {
                    currency: "EUR",
                    amount: 40,
                  },
                  senior_price: {
                    currency: "EUR",
                    amount: 50,
                  },
                },
                duration_minutes: 120,
                available_times: [
                  {
                    date: "2026-05-07",
                    time: "14:00",
                    available_spots: 20,
                  },
                  {
                    date: "2026-05-08",
                    time: "14:00",
                    available_spots: 18,
                  },
                  {
                    date: "2026-05-09",
                    time: "14:00",
                    available_spots: 22,
                  },
                ],
                highlights: [
                  "See Botticelli’s Venus and Primavera",
                  "Skip long lines with timed entry",
                  "In-depth guide on Renaissance art",
                ],
                included: [
                  "Skip-the-line entry",
                  "Professional guide",
                  "Audioguide option",
                ],
                excluded: [
                  "Food and drinks",
                  "Transportation",
                  "Photos with flash",
                ],
                min_participants: 1,
                max_participants: 25,
                difficulty_level: "easy",
                hotel_pickup: false,
                meal_included: false,
                cancellation_policy: "Free cancellation up to 48 hours before",
                scores: {
                  price_score: 0.85,
                  quality_score: 0.98,
                  convenience_score: 0.9,
                  preference_score: 1,
                },
                booking_url: "https://example.com/book/uffizi-002",
                provider: "Uffizi Official Partners",
                available: true,
                image_urls: [
                  "https://example.com/images/uffizi1.jpg",
                  "https://example.com/images/uffizi2.jpg",
                ],
              },
              {
                id: "tuscan-food-walk-003",
                name: "Tuscan Cuisine Food Tour with Ponte Vecchio Sunset",
                description:
                  "Taste authentic Tuscan cuisine on a walking food tour through historic Florence, featuring bistecca alla fiorentina, wine tasting, and gelato, ending with sunset views from Ponte Vecchio.",
                category: 12,
                location: {
                  city: "Florence",
                  country: "IT",
                  airport_code: "FLR",
                  latitude: 43.768,
                  longitude: 11.2532,
                },
                distance_from_query_km: 0.3,
                rating: 4.9,
                review_count: 1200,
                price_per_person: {
                  currency: "EUR",
                  amount: 85,
                },
                price_details: {
                  adult_price: {
                    currency: "EUR",
                    amount: 85,
                  },
                  child_price: {
                    currency: "EUR",
                    amount: 65,
                  },
                  senior_price: {
                    currency: "EUR",
                    amount: 75,
                  },
                },
                duration_minutes: 210,
                available_times: [
                  {
                    date: "2026-05-07",
                    time: "17:30",
                    available_spots: 10,
                  },
                  {
                    date: "2026-05-08",
                    time: "17:30",
                    available_spots: 8,
                  },
                  {
                    date: "2026-05-09",
                    time: "17:30",
                    available_spots: 12,
                  },
                ],
                highlights: [
                  "Sample bistecca alla fiorentina and Chianti wine",
                  "Visit Ponte Vecchio at golden hour",
                  "Local hidden eateries and stories",
                ],
                included: [
                  "6-8 food tastings",
                  "Wine samples",
                  "English-speaking foodie guide",
                ],
                excluded: ["Hotel transfers", "Extra drinks", "Souvenirs"],
                min_participants: 2,
                max_participants: 12,
                difficulty_level: "easy",
                hotel_pickup: false,
                meal_included: true,
                cancellation_policy: "Free cancellation up to 24 hours before",
                scores: {
                  price_score: 0.8,
                  quality_score: 0.92,
                  convenience_score: 0.88,
                  preference_score: 1,
                },
                booking_url: "https://example.com/book/foodtour-003",
                provider: "Eat Like a Local",
                available: true,
                image_urls: [
                  "https://example.com/images/foodtour1.jpg",
                  "https://example.com/images/foodtour2.jpg",
                  "https://example.com/images/pontevecchio.jpg",
                ],
              },
            ],
          },
        },
        {
          type: SectionType.STAY,
          data: {
            hotel: {
              id: "1cdd5dd5-9135-5c68-9a74-acd59772de01",
              name: "CHC Continental, BW Premier Collection",
              description:
                "Discover an unforgettable experience at CHC Continental, BW Premier Collection, nestled in the heart of Venice, just a stroll away from iconic landmarks like the Grand Canal.Modern ComfortsRelax in one of our 93 air-conditioned rooms, each thoughtfully designed with minibars, flat-screen TVs, and complimentary wireless internet access, ensuring a rejuvenating stay with all the modern amenities at your fingertips.Delectable DiningIndulge in delightful culinary offerings at our on-site restaurant,",
              location: {
                city: "Venice",
                country: "IT",
                airport_code: "",
                latitude: 45.44217,
                longitude: 12.32378,
              },
              distance_to_center_km: 2.5,
              image: "https://static.cupid.travel/hotels/ex_103dd99f_z.jpg",
              rating: 8.2,
              review_count: 139,
              rating_category: "Excellent",
              price_per_night: {
                currency: "USD",
                amount: 425.5233333333333,
              },
              total_price: {
                currency: "USD",
                amount: 1276.57,
              },
              additional_fees: [
                {
                  name: "Mandatory Fee",
                  amount: {
                    currency: "USD",
                    amount: 31.62,
                  },
                  mandatory: true,
                },
              ],
              room: {
                type: "1 Queen Bed",
                beds: 1,
                bed_type: "standard",
                max_occupancy: 2,
                size_sqm: 0,
                features: [],
              },
              amenities: [
                "Facility_1842",
                "Facility_107",
                "Facility_8",
                "Facility_15",
                "Facility_91",
                "Facility_49",
                "Facility_124",
                "Facility_185",
                "Facility_491",
                "Facility_519",
              ],
              category: "upscale",
              star_rating: 4,
              scores: {
                price_score: 0.1655037037037037,
                quality_score: 0.82,
                convenience_score: 0.75,
                preference_score: 0.5,
              },
              booking_url: "https://booking.liteapi.travel/hotels/lp1b543",
              provider: "nuitee",
              available: true,
            },
            activities: [
              {
                id: "venice-gondola-ride-001",
                name: "Grand Canal Gondola Experience with Live Commentary",
                description:
                  "Enjoy a guided gondola ride through Venice’s small canals and the Grand Canal. Glide in a traditional black gondola while your tour guide shares commentary about the palaces, their stories, and the traditions of gondolas and gondoliers.",
                category: 1,
                location: {
                  city: "Venice",
                  country: "IT",
                  airport_code: "VCE",
                  latitude: 45.4408,
                  longitude: 12.3155,
                },
                distance_from_query_km: 0.5,
                rating: 4.8,
                review_count: 1250,
                price_per_person: {
                  currency: "EUR",
                  amount: 85,
                },
                price_details: {
                  adult_price: {
                    currency: "EUR",
                    amount: 85,
                  },
                  child_price: {
                    currency: "EUR",
                    amount: 45,
                  },
                  senior_price: {
                    currency: "EUR",
                    amount: 75,
                  },
                },
                duration_minutes: 30,
                available_times: [
                  {
                    date: "2026-05-09",
                    time: "10:00",
                    available_spots: 10,
                  },
                  {
                    date: "2026-05-10",
                    time: "14:00",
                    available_spots: 8,
                  },
                  {
                    date: "2026-05-11",
                    time: "16:00",
                    available_spots: 12,
                  },
                ],
                highlights: [
                  "Live commentary on palaces and history",
                  "Pass by Mozart’s House and La Fenice Theatre",
                  "Traditional black gondola ride",
                ],
                included: ["Professional gondolier guide", "30-minute ride"],
                excluded: ["Gratuities", "Food and drinks"],
                min_participants: 1,
                max_participants: 6,
                difficulty_level: "easy",
                hotel_pickup: false,
                meal_included: false,
                cancellation_policy:
                  "Free cancellation up to 24 hours in advance",
                scores: {
                  price_score: 0.9,
                  quality_score: 0.95,
                  convenience_score: 0.85,
                  preference_score: 1,
                },
                booking_url:
                  "https://www.getyourguide.com/venice-l35/venice-grand-canal-gondola-experience-p1234",
                provider: "GetYourGuide",
                available: true,
                image_urls: [
                  "https://example.com/gondola1.jpg",
                  "https://example.com/gondola2.jpg",
                ],
              },
              {
                id: "doge-stmark-tour-002",
                name: "Doge's Palace & St. Mark's Basilica Skip-the-Line Tour",
                description:
                  "Explore the iconic Doge's Palace and St. Mark's Basilica with skip-the-line access and expert local guide, uncovering the history of Venice's power centers.",
                category: 1,
                location: {
                  city: "Venice",
                  country: "IT",
                  airport_code: "VCE",
                  latitude: 45.4345,
                  longitude: 12.3398,
                },
                distance_from_query_km: 0.2,
                rating: 4.7,
                review_count: 3400,
                price_per_person: {
                  currency: "EUR",
                  amount: 45,
                },
                price_details: {
                  adult_price: {
                    currency: "EUR",
                    amount: 45,
                  },
                  child_price: {
                    currency: "EUR",
                    amount: 25,
                  },
                  senior_price: {
                    currency: "EUR",
                    amount: 40,
                  },
                },
                duration_minutes: 120,
                available_times: [
                  {
                    date: "2026-05-09",
                    time: "09:30",
                    available_spots: 15,
                  },
                  {
                    date: "2026-05-10",
                    time: "11:00",
                    available_spots: 12,
                  },
                  {
                    date: "2026-05-11",
                    time: "15:00",
                    available_spots: 18,
                  },
                ],
                highlights: [
                  "Skip-the-line entry",
                  "Guided tour of both landmarks",
                  "Terrace access at St. Mark's",
                ],
                included: ["Entrance tickets", "Expert guide"],
                excluded: ["Lunch", "Private transport"],
                min_participants: 1,
                max_participants: 20,
                difficulty_level: "easy",
                hotel_pickup: false,
                meal_included: false,
                cancellation_policy:
                  "Free cancellation up to 24 hours in advance",
                scores: {
                  price_score: 0.92,
                  quality_score: 0.96,
                  convenience_score: 0.88,
                  preference_score: 0.98,
                },
                booking_url:
                  "https://www.getyourguide.com/venice-l35/doges-palace-st-marks-tour-p567",
                provider: "GetYourGuide",
                available: true,
                image_urls: [
                  "https://example.com/doge1.jpg",
                  "https://example.com/stmarks1.jpg",
                ],
              },
              {
                id: "venice-canals-boat-003",
                name: "Venice Canals and Lagoon Boat Tour",
                description:
                  "Discover Venice's canals, Grand Canal highlights, and nearby islands like Murano on a panoramic boat tour, perfect for seeing the city's waterways.",
                category: 5,
                location: {
                  city: "Venice",
                  country: "IT",
                  airport_code: "VCE",
                  latitude: 45.4408,
                  longitude: 12.3155,
                },
                distance_from_query_km: 0.1,
                rating: 4.6,
                review_count: 2100,
                price_per_person: {
                  currency: "EUR",
                  amount: 32,
                },
                price_details: {
                  adult_price: {
                    currency: "EUR",
                    amount: 32,
                  },
                  child_price: {
                    currency: "EUR",
                    amount: 16,
                  },
                  senior_price: {
                    currency: "EUR",
                    amount: 28,
                  },
                },
                duration_minutes: 180,
                available_times: [
                  {
                    date: "2026-05-09",
                    time: "13:00",
                    available_spots: 20,
                  },
                  {
                    date: "2026-05-10",
                    time: "09:00",
                    available_spots: 22,
                  },
                  {
                    date: "2026-05-12",
                    time: "11:30",
                    available_spots: 18,
                  },
                ],
                highlights: [
                  "Panoramic views of canals",
                  "Visit to Murano glass factory",
                  "Comfortable boat ride",
                ],
                included: ["Boat tour", "Audio guide"],
                excluded: ["Glass purchases", "Meals"],
                min_participants: 1,
                max_participants: 50,
                difficulty_level: "easy",
                hotel_pickup: false,
                meal_included: false,
                cancellation_policy:
                  "Free cancellation up to 24 hours in advance",
                scores: {
                  price_score: 0.95,
                  quality_score: 0.9,
                  convenience_score: 0.92,
                  preference_score: 0.95,
                },
                booking_url:
                  "https://www.getyourguide.com/venice-l35/venice-lagoon-boat-tour-p890",
                provider: "GetYourGuide",
                available: true,
                image_urls: [
                  "https://example.com/boat1.jpg",
                  "https://example.com/lagoon1.jpg",
                ],
              },
            ],
          },
        },
        {
          type: SectionType.FLIGHT,
          data: {
            id: "7ea4aa97-216f-562b-90ba-1af686893c46",
            outbound: {
              origin: {
                city: "",
                country: "IT",
                airport_code: "VCE",
                latitude: 0,
                longitude: 0,
              },
              destination: {
                city: "",
                country: "IL",
                airport_code: "TLV",
                latitude: 0,
                longitude: 0,
              },
              departure_time: "2026-05-12T22:00:00",
              arrival_time: "2026-05-13T02:25:00",
              duration_minutes: 205,
              stops: 0,
              layovers: [],
              airline: "LY",
              flight_number: "LY290",
              aircraft: "738",
              cabin_class: "economy",
              amenities: {
                wifi: false,
                meal: true,
                entertainment: false,
                power_outlet: false,
                legroom_inches: 0,
              },
              luggage: {
                checked_bags: 0,
                checked_bag_weight_kg: 0,
                carry_on_bags: 1,
                carry_on_weight_kg: 0,
                carry_on_dimensions_cm: "",
              },
            },
            total_price: {
              currency: "EUR",
              amount: 359.36,
            },
            price_per_person: {
              currency: "EUR",
              amount: 179.68,
            },
            scores: {
              price_score: 0.7806166577475346,
              quality_score: 0,
              convenience_score: 0,
              preference_score: 0.7944880888672866,
            },
            booking_url: "",
            provider: "LY",
            available: true,
          },
        },
      ],
    },
  },
  {
    vibe: "Southern Hidden Gems Trail",
    layout: {
      sections: [
        {
          type: SectionType.FLIGHT,
          data: {
            id: "438eaa5f-f0e6-54c4-a93d-2e26db679291",
            outbound: {
              origin: {
                city: "",
                country: "IL",
                airport_code: "TLV",
                latitude: 0,
                longitude: 0,
              },
              destination: {
                city: "",
                country: "IT",
                airport_code: "NAP",
                latitude: 0,
                longitude: 0,
              },
              departure_time: "2026-05-05T05:15:00",
              arrival_time: "2026-05-05T10:35:00",
              duration_minutes: 380,
              stops: 1,
              layovers: [
                {
                  airport: {
                    city: "",
                    country: "IT",
                    airport_code: "FCO",
                    latitude: 0,
                    longitude: 0,
                  },
                  start_time: "2026-05-05T08:00:00",
                  end_time: "2026-05-05T09:40:00",
                  duration_minutes: 100,
                  arrival_terminal: "3",
                  departure_terminal: "1",
                  airline_before: "AZ",
                  airline_after: "AZ",
                  is_airline_change: false,
                  is_terminal_change: true,
                  overnight: false,
                },
              ],
              airline: "AZ",
              flight_number: "AZ809",
              aircraft: "32Q",
              cabin_class: "economy",
              amenities: {
                wifi: false,
                meal: false,
                entertainment: false,
                power_outlet: false,
                legroom_inches: 0,
              },
              luggage: {
                checked_bags: 0,
                checked_bag_weight_kg: 0,
                carry_on_bags: 1,
                carry_on_weight_kg: 0,
                carry_on_dimensions_cm: "",
              },
            },
            total_price: {
              currency: "EUR",
              amount: 314.1,
            },
            price_per_person: {
              currency: "EUR",
              amount: 157.05,
            },
            scores: {
              price_score: 0.7135183357717749,
              quality_score: 0,
              convenience_score: 0,
              preference_score: 0.6477511922179344,
            },
            booking_url: "",
            provider: "AZ",
            available: true,
          },
        },
        {
          type: SectionType.STAY,
          data: {
            hotel: {
              id: "266965fe-5bad-5eaf-8c9b-03931535e586",
              name: "Grand Hotel Santa Lucia",
              description:
                "Luxurious Accommodation with Stunning ViewsArt-Nouveau Design and Modern AmenitiesStep into a world of elegance with the impressive Art-Nouveau design of Grand Hotel Santa Lucia. Enjoy modern amenities such as a well-equipped gym to cater to your fitness needs during your stay.Gourmet Dining Experience with Spectacular ViewsIndulge in a culinary journey at the stylish hotel restaurant offering creative, contemporary dishes alongside Neapolitan favorites. Pair your meal with a fine wine from the ",
              location: {
                city: "Naples",
                country: "it",
                airport_code: "",
                latitude: 40.829966,
                longitude: 14.249104,
              },
              distance_to_center_km: 2.5,
              image: "https://static.cupid.travel/hotels/20444083.jpg",
              rating: 9,
              review_count: 529,
              rating_category: "Exceptional",
              price_per_night: {
                currency: "USD",
                amount: 406.355,
              },
              total_price: {
                currency: "USD",
                amount: 812.71,
              },
              additional_fees: [
                {
                  name: "Mandatory Tax",
                  amount: {
                    currency: "USD",
                    amount: 23.32,
                  },
                  mandatory: true,
                },
              ],
              room: {
                type: "Classic Room",
                beds: 1,
                bed_type: "standard",
                max_occupancy: 2,
                size_sqm: 0,
                features: [],
              },
              amenities: [
                "Facility_6848",
                "Facility_16",
                "Facility_109",
                "Facility_3",
                "Facility_5",
                "Facility_28",
                "Facility_4",
                "Facility_48",
                "Facility_91",
                "Facility_51",
              ],
              category: "luxury",
              star_rating: 4,
              scores: {
                price_score: 0.20809999999999995,
                quality_score: 0.9,
                convenience_score: 0.75,
                preference_score: 0.5,
              },
              booking_url: "https://booking.liteapi.travel/hotels/lp1b0dc",
              provider: "nuitee",
              available: true,
            },
            activities: [
              {
                id: "naples-foodtour-001",
                name: "Authentic Naples Street Food Tour with Local Guide",
                description:
                  "Explore downtown Naples on a guided street food tour, tasting local specialties like zucchini flowers, ragù, baccalà, fried pizza, and more while visiting historic squares and hidden eateries.",
                category: 12,
                location: {
                  city: "Naples",
                  country: "IT",
                  airport_code: "NAP",
                  latitude: 40.8518,
                  longitude: 14.2681,
                },
                distance_from_query_km: 0.5,
                rating: 4.8,
                review_count: 1250,
                price_per_person: {
                  currency: "EUR",
                  amount: 50,
                },
                price_details: {
                  adult_price: {
                    currency: "EUR",
                    amount: 50,
                  },
                  child_price: {
                    currency: "EUR",
                    amount: 35,
                  },
                  senior_price: {
                    currency: "EUR",
                    amount: 45,
                  },
                },
                duration_minutes: 150,
                available_times: [
                  {
                    date: "2026-05-05",
                    time: "10:00",
                    available_spots: 12,
                  },
                  {
                    date: "2026-05-06",
                    time: "18:00",
                    available_spots: 10,
                  },
                  {
                    date: "2026-05-07",
                    time: "10:00",
                    available_spots: 12,
                  },
                ],
                highlights: [
                  "Taste authentic street foods like fried pizza and baccalà",
                  "Visit Piazza Bellini and Via dei Tribunali",
                  "Professional local guide sharing Naples history",
                ],
                included: [
                  "Multiple food tastings",
                  "Spritz tasting",
                  "Guided walking tour",
                  "Gratuities",
                ],
                excluded: ["Extra drinks", "Hotel pickup", "Transportation"],
                min_participants: 1,
                max_participants: 15,
                difficulty_level: "easy",
                hotel_pickup: false,
                meal_included: true,
                cancellation_policy:
                  "Free cancellation up to 24 hours in advance",
                scores: {
                  price_score: 0.9,
                  quality_score: 0.95,
                  convenience_score: 0.85,
                  preference_score: 1,
                },
                booking_url:
                  "https://www.viator.com/tours/Naples/Downtown-Naples-Food-and-Wine-Tour/d508-20455P6",
                provider: "Viator",
                available: true,
                image_urls: [
                  "https://www.viator.com/assets/destinations/508/20455P6.jpg",
                  "https://www.viator.com/assets/destinations/508/street-food-naples.jpg",
                ],
              },
              {
                id: "naples-underground-002",
                name: "Naples Underground Tour: Ancient Tunnels and Aqueducts",
                description:
                  "Descend into the ancient underground world of Naples, exploring Greek-Roman aqueducts, WWII shelters, and hidden tunnels beneath the historic center with an expert guide.",
                category: 1,
                location: {
                  city: "Naples",
                  country: "IT",
                  airport_code: "NAP",
                  latitude: 40.8523,
                  longitude: 14.2608,
                },
                distance_from_query_km: 0.3,
                rating: 4.7,
                review_count: 850,
                price_per_person: {
                  currency: "EUR",
                  amount: 25,
                },
                price_details: {
                  adult_price: {
                    currency: "EUR",
                    amount: 25,
                  },
                  child_price: {
                    currency: "EUR",
                    amount: 15,
                  },
                  senior_price: {
                    currency: "EUR",
                    amount: 22,
                  },
                },
                duration_minutes: 90,
                available_times: [
                  {
                    date: "2026-05-05",
                    time: "11:00",
                    available_spots: 15,
                  },
                  {
                    date: "2026-05-06",
                    time: "14:00",
                    available_spots: 12,
                  },
                  {
                    date: "2026-05-07",
                    time: "16:00",
                    available_spots: 15,
                  },
                ],
                highlights: [
                  "Explore 2,500-year-old underground aqueducts",
                  "Discover secret WWII bomb shelters",
                  "Small group tour with headsets",
                ],
                included: [
                  "Expert guide",
                  "Entrance to underground sites",
                  "Audio headsets",
                ],
                excluded: ["Hotel pickup", "Meals", "Photos"],
                min_participants: 1,
                max_participants: 20,
                difficulty_level: "moderate",
                hotel_pickup: false,
                meal_included: false,
                cancellation_policy:
                  "Free cancellation up to 24 hours in advance",
                scores: {
                  price_score: 0.95,
                  quality_score: 0.9,
                  convenience_score: 0.8,
                  preference_score: 0.95,
                },
                booking_url: "https://www.naplesunderground.org/en/",
                provider: "Naples Underground",
                available: true,
                image_urls: [
                  "https://naplesunderground.org/wp-content/uploads/tour-underground.jpg",
                  "https://naplesunderground.org/wp-content/uploads/aqueducts-naples.jpg",
                ],
              },
              {
                id: "naples-foodunderground-003",
                name: "Street Food and Underground Combo Tour",
                description:
                  "Combine the best of Naples with street food tastings in historic markets and an underground exploration of ancient tunnels, guided by local experts.",
                category: 12,
                location: {
                  city: "Naples",
                  country: "IT",
                  airport_code: "NAP",
                  latitude: 40.8505,
                  longitude: 14.2584,
                },
                distance_from_query_km: 0.8,
                rating: 4.9,
                review_count: 320,
                price_per_person: {
                  currency: "EUR",
                  amount: 85,
                },
                price_details: {
                  adult_price: {
                    currency: "EUR",
                    amount: 85,
                  },
                  child_price: {
                    currency: "EUR",
                    amount: 60,
                  },
                  senior_price: {
                    currency: "EUR",
                    amount: 78,
                  },
                },
                duration_minutes: 240,
                available_times: [
                  {
                    date: "2026-05-05",
                    time: "09:00",
                    available_spots: 8,
                  },
                  {
                    date: "2026-05-06",
                    time: "15:00",
                    available_spots: 10,
                  },
                  {
                    date: "2026-05-07",
                    time: "09:00",
                    available_spots: 8,
                  },
                ],
                highlights: [
                  "Street food in Quartieri Spagnoli market",
                  "Underground tunnels and ancient ruins",
                  "Comprehensive cultural and culinary experience",
                ],
                included: [
                  "Food tastings and market visits",
                  "Underground tour entrance",
                  "Local guide",
                ],
                excluded: ["Drinks beyond tastings", "Hotel pickup"],
                min_participants: 2,
                max_participants: 12,
                difficulty_level: "moderate",
                hotel_pickup: false,
                meal_included: true,
                cancellation_policy:
                  "Free cancellation up to 48 hours in advance",
                scores: {
                  price_score: 0.85,
                  quality_score: 0.98,
                  convenience_score: 0.9,
                  preference_score: 1,
                },
                booking_url:
                  "https://www.streaty.com/city/street-food-tours-in-naples/",
                provider: "Streaty",
                available: true,
                image_urls: [
                  "https://www.streaty.com/wp-content/uploads/naples-market-tour.jpg",
                  "https://www.streaty.com/wp-content/uploads/naples-underground-food.jpg",
                ],
              },
            ],
          },
        },
        {
          type: SectionType.STAY,
          data: {
            hotel: {
              id: "b934eaea-621c-51d0-98fd-6e8521da45b4",
              name: "Hotel Del Campo",
              description:
                "Historical Building with Modern ComfortsHotel Del Campo, a historical gem just outside Matera's city centre, offers a unique blend of old-world charm and modern amenities. The 18th-century building, meticulously renovated, boasts spacious rooms with free Wi-Fi, parquet floors, and air conditioning, providing guests with a comfortable stay.Le Spighe Restaurant and Lush GardensIndulge in local cuisine at Le Spighe Restaurant, nestled in a picturesque park within the hotel grounds. Savor the flavor",
              location: {
                city: "Matera",
                country: "it",
                airport_code: "",
                latitude: 40.681114,
                longitude: 16.583924,
              },
              distance_to_center_km: 2.5,
              image: "https://static.cupid.travel/hotels/269567859.jpg",
              rating: 8.6,
              review_count: 685,
              rating_category: "Excellent",
              price_per_night: {
                currency: "USD",
                amount: 134.31,
              },
              total_price: {
                currency: "USD",
                amount: 402.93,
              },
              additional_fees: [],
              room: {
                type: "Standard Twin",
                beds: 1,
                bed_type: "standard",
                max_occupancy: 2,
                size_sqm: 0,
                features: [],
              },
              amenities: [
                "Facility_2083",
                "Facility_16",
                "Facility_109",
                "Facility_301",
                "Facility_5",
                "Facility_15",
                "Facility_28",
                "Facility_48",
                "Facility_49",
                "Facility_51",
              ],
              category: "upscale",
              star_rating: 4,
              scores: {
                price_score: 0.8126444444444445,
                quality_score: 0.86,
                convenience_score: 0.75,
                preference_score: 0.5,
              },
              booking_url: "https://booking.liteapi.travel/hotels/lp2f3e6",
              provider: "nuitee",
              available: true,
            },
            activities: [
              {
                id: "act_001",
                name: "Sassi di Matera Guided Walking Tour",
                description:
                  "Explore the ancient Sassi districts of Barisano and Caveoso with a local guide, visiting cave dwellings, rock churches, and panoramic viewpoints in Matera's UNESCO site.",
                category: 1,
                location: {
                  city: "Matera",
                  country: "IT",
                  airport_code: "BDS",
                  latitude: 40.668,
                  longitude: 16.6025,
                },
                distance_from_query_km: 0,
                rating: 4.8,
                review_count: 1250,
                price_per_person: {
                  currency: "EUR",
                  amount: 45,
                },
                price_details: {
                  adult_price: {
                    currency: "EUR",
                    amount: 45,
                  },
                  child_price: {
                    currency: "EUR",
                    amount: 25,
                  },
                  senior_price: {
                    currency: "EUR",
                    amount: 40,
                  },
                },
                duration_minutes: 120,
                available_times: [
                  {
                    date: "2026-05-07",
                    time: "09:00",
                    available_spots: 15,
                  },
                  {
                    date: "2026-05-08",
                    time: "14:00",
                    available_spots: 12,
                  },
                  {
                    date: "2026-05-09",
                    time: "10:00",
                    available_spots: 18,
                  },
                ],
                highlights: [
                  "Visit Sasso Caveoso and Sasso Barisano ancient neighborhoods",
                  "Explore preserved cave dwelling museum",
                  "See rock-hewn churches like San Pietro Caveoso",
                ],
                included: [
                  "Local English-speaking guide",
                  "Entrance to Casa Grotta cave house",
                  "Entrance to one rupestrian church",
                ],
                excluded: [
                  "Meals and drinks",
                  "Hotel pickup",
                  "Personal expenses",
                ],
                min_participants: 1,
                max_participants: 15,
                difficulty_level: "easy",
                hotel_pickup: false,
                meal_included: false,
                cancellation_policy: "Free cancellation up to 24 hours before",
                scores: {
                  price_score: 0.85,
                  quality_score: 0.92,
                  convenience_score: 0.88,
                  preference_score: 0.95,
                },
                booking_url:
                  "https://www.martulliviaggi.com/en/tour/matera-walking-guided-tour/",
                provider: "Martulli Viaggi",
                available: true,
                image_urls: [
                  "https://example.com/sassi-tour1.jpg",
                  "https://example.com/sassi-tour2.jpg",
                ],
              },
              {
                id: "act_002",
                name: "Cave Dwellings and Sassi Hiking Adventure",
                description:
                  "Moderate hike through the rugged Sasso Caveoso quarter, exploring ancient cave houses like Casa Grotta di Vico Solitario and hidden paths with stunning ravine views.",
                category: 5,
                location: {
                  city: "Matera",
                  country: "IT",
                  airport_code: "BDS",
                  latitude: 40.665,
                  longitude: 16.605,
                },
                distance_from_query_km: 0.5,
                rating: 4.6,
                review_count: 850,
                price_per_person: {
                  currency: "EUR",
                  amount: 65,
                },
                price_details: {
                  adult_price: {
                    currency: "EUR",
                    amount: 65,
                  },
                  child_price: {
                    currency: "EUR",
                    amount: 40,
                  },
                  senior_price: {
                    currency: "EUR",
                    amount: 55,
                  },
                },
                duration_minutes: 180,
                available_times: [
                  {
                    date: "2026-05-07",
                    time: "08:30",
                    available_spots: 10,
                  },
                  {
                    date: "2026-05-09",
                    time: "16:00",
                    available_spots: 8,
                  },
                  {
                    date: "2026-05-10",
                    time: "09:30",
                    available_spots: 12,
                  },
                ],
                highlights: [
                  "Hike rugged paths in Sasso Caveoso",
                  "Enter reconstructed Casa Grotta di Vico Solitario",
                  "Panoramic views of Gravina gorge",
                ],
                included: [
                  "Professional guide",
                  "Entrance fees to cave sites",
                  "Water and snacks",
                ],
                excluded: ["Lunch", "Transportation", "Tips"],
                min_participants: 2,
                max_participants: 12,
                difficulty_level: "moderate",
                hotel_pickup: true,
                meal_included: false,
                cancellation_policy: "Free cancellation up to 48 hours before",
                scores: {
                  price_score: 0.78,
                  quality_score: 0.9,
                  convenience_score: 0.82,
                  preference_score: 0.92,
                },
                booking_url:
                  "https://www.getyourguide.com/sassi-di-matera-l89408/",
                provider: "GetYourGuide",
                available: true,
                image_urls: [
                  "https://example.com/hike-sassi1.jpg",
                  "https://example.com/hike-sassi2.jpg",
                ],
              },
              {
                id: "act_003",
                name: "Private Sassi Cave Houses and Rock Churches Tour",
                description:
                  "Private guided exploration of Matera's cave dwellings, including visits to ancient sassi homes, rupestrian churches, and lesser-known cave sites with historical insights.",
                category: 1,
                location: {
                  city: "Matera",
                  country: "IT",
                  airport_code: "BDS",
                  latitude: 40.67,
                  longitude: 16.6,
                },
                distance_from_query_km: 0.3,
                rating: 4.9,
                review_count: 650,
                price_per_person: {
                  currency: "EUR",
                  amount: 120,
                },
                price_details: {
                  adult_price: {
                    currency: "EUR",
                    amount: 120,
                  },
                  child_price: {
                    currency: "EUR",
                    amount: 80,
                  },
                  senior_price: {
                    currency: "EUR",
                    amount: 110,
                  },
                },
                duration_minutes: 150,
                available_times: [
                  {
                    date: "2026-05-08",
                    time: "11:00",
                    available_spots: 6,
                  },
                  {
                    date: "2026-05-09",
                    time: "15:00",
                    available_spots: 6,
                  },
                  {
                    date: "2026-05-10",
                    time: "10:00",
                    available_spots: 6,
                  },
                ],
                highlights: [
                  "Private tour of Sassi Barisano and Caveoso",
                  "Access to Casa Grotta and San Antonio Abate church",
                  "Stories of ancient cave inhabitants",
                ],
                included: [
                  "Private local guide",
                  "All entrance fees",
                  "Customized itinerary",
                ],
                excluded: ["Meals", "Hotel transfers", "Photos"],
                min_participants: 1,
                max_participants: 6,
                difficulty_level: "easy",
                hotel_pickup: true,
                meal_included: false,
                cancellation_policy: "Free cancellation up to 24 hours before",
                scores: {
                  price_score: 0.7,
                  quality_score: 0.96,
                  convenience_score: 0.95,
                  preference_score: 0.9,
                },
                booking_url: "https://sassidimatera.it/en/",
                provider: "Sassi di Matera Guides",
                available: true,
                image_urls: [
                  "https://example.com/private-sassi1.jpg",
                  "https://example.com/private-sassi2.jpg",
                ],
              },
            ],
          },
        },
        {
          type: SectionType.FLIGHT,
          data: {
            id: "28264c75-c5fd-50fc-b1f2-2f5f94740e96",
            outbound: {
              origin: {
                city: "",
                country: "IT",
                airport_code: "BRI",
                latitude: 0,
                longitude: 0,
              },
              destination: {
                city: "",
                country: "IL",
                airport_code: "TLV",
                latitude: 0,
                longitude: 0,
              },
              departure_time: "2026-05-10T06:30:00",
              arrival_time: "2026-05-10T13:30:00",
              duration_minutes: 360,
              stops: 1,
              layovers: [
                {
                  airport: {
                    city: "",
                    country: "IT",
                    airport_code: "FCO",
                    latitude: 0,
                    longitude: 0,
                  },
                  start_time: "2026-05-10T07:40:00",
                  end_time: "2026-05-10T09:10:00",
                  duration_minutes: 90,
                  arrival_terminal: "1",
                  departure_terminal: "1",
                  airline_before: "AZ",
                  airline_after: "AZ",
                  is_airline_change: false,
                  is_terminal_change: false,
                  overnight: false,
                },
              ],
              airline: "AZ",
              flight_number: "AZ1602",
              aircraft: "32N",
              cabin_class: "economy",
              amenities: {
                wifi: false,
                meal: false,
                entertainment: false,
                power_outlet: false,
                legroom_inches: 0,
              },
              luggage: {
                checked_bags: 0,
                checked_bag_weight_kg: 0,
                carry_on_bags: 1,
                carry_on_weight_kg: 0,
                carry_on_dimensions_cm: "",
              },
            },
            total_price: {
              currency: "EUR",
              amount: 506.02,
            },
            price_per_person: {
              currency: "EUR",
              amount: 253.01,
            },
            scores: {
              price_score: 0.6413135181312045,
              quality_score: 0,
              convenience_score: 0,
              preference_score: 0.6009382272365746,
            },
            booking_url: "",
            provider: "AZ",
            available: true,
          },
        },
      ],
    },
  },
  {
    vibe: "Nature Coast Wellness Trail",
    layout: {
      sections: [
        {
          type: SectionType.FLIGHT,
          data: {
            id: "a1a76107-79b3-5b3b-9b9b-f0826e9ac765",
            outbound: {
              origin: {
                city: "",
                country: "IL",
                airport_code: "TLV",
                latitude: 0,
                longitude: 0,
              },
              destination: {
                city: "",
                country: "IT",
                airport_code: "FCO",
                latitude: 0,
                longitude: 0,
              },
              departure_time: "2026-05-05T18:00:00",
              arrival_time: "2026-05-05T20:40:00",
              duration_minutes: 220,
              stops: 0,
              layovers: [],
              airline: "LY",
              flight_number: "LY383",
              aircraft: "738",
              cabin_class: "economy",
              amenities: {
                wifi: false,
                meal: true,
                entertainment: false,
                power_outlet: false,
                legroom_inches: 0,
              },
              luggage: {
                checked_bags: 0,
                checked_bag_weight_kg: 0,
                carry_on_bags: 1,
                carry_on_weight_kg: 0,
                carry_on_dimensions_cm: "",
              },
            },
            total_price: {
              currency: "EUR",
              amount: 284.68,
            },
            price_per_person: {
              currency: "EUR",
              amount: 142.34,
            },
            scores: {
              price_score: 0.806206922228441,
              quality_score: 0,
              convenience_score: 0,
              preference_score: 0.8091954206393627,
            },
            booking_url: "",
            provider: "LY",
            available: true,
          },
        },
        {
          type: SectionType.STAY,
          data: {
            hotel: {
              id: "ca399b48-ca7c-5b55-b58e-6e057dae1d2f",
              name: "Hotel Lord Byron",
              description:
                "Experience the elegance of Hotel Lord Byron, an Art Deco gem nestled in the heart of Rome, where sophistication meets comfort.Luxurious AccommodationsRelax in one of our 28 stylish guestrooms, featuring memory foam beds, premium bedding, and modern amenities such as LCD televisions and minibars. Each room is designed for your utmost comfort, with complimentary toiletries and high-speed wireless internet access.Gastronomic DelightsIndulge in culinary excellence at our on-site restaurant, Sapori d",
              location: {
                city: "Rome",
                country: "IT",
                airport_code: "",
                latitude: 41.919861,
                longitude: 12.481478,
              },
              distance_to_center_km: 2.5,
              image: "https://static.cupid.travel/hotels/ex_73af06d5_z.jpg",
              rating: 9,
              review_count: 132,
              rating_category: "Exceptional",
              price_per_night: {
                currency: "USD",
                amount: 514.97,
              },
              total_price: {
                currency: "USD",
                amount: 1029.94,
              },
              additional_fees: [
                {
                  name: "mandatory tax",
                  amount: {
                    currency: "USD",
                    amount: 41.02,
                  },
                  mandatory: true,
                },
              ],
              room: {
                type: "Superior Room",
                beds: 1,
                bed_type: "standard",
                max_occupancy: 2,
                size_sqm: 0,
                features: [],
              },
              amenities: [
                "Facility_1054",
                "Facility_1091",
                "Facility_2020",
                "Facility_2050",
                "Facility_2247",
                "Facility_2253",
                "Facility_2259",
                "Facility_2261",
                "Facility_2411",
                "Facility_107",
              ],
              category: "luxury",
              star_rating: 5,
              scores: {
                price_score: 0,
                quality_score: 0.9,
                convenience_score: 0.75,
                preference_score: 0.5,
              },
              booking_url: "https://booking.liteapi.travel/hotels/lp19be2",
              provider: "nuitee",
              available: true,
            },
            activities: [
              {
                id: "spa-ostia-antica-park-1",
                name: "Otium Spa Relaxation Package",
                description:
                  "Indulge in a full spa experience at Ostia Antica Park Hotel & Spa featuring sauna, Turkish bath, whirlpool, and relaxation area with sea views, perfect for unwinding after beach time.",
                category: 9,
                location: {
                  city: "Ostia Antica",
                  country: "Italy",
                  airport_code: "FCO",
                  latitude: 41.75,
                  longitude: 12.3067,
                },
                distance_from_query_km: 5,
                rating: 4.2,
                review_count: 450,
                price_per_person: {
                  currency: "EUR",
                  amount: 85,
                },
                price_details: {
                  adult_price: {
                    currency: "EUR",
                    amount: 85,
                  },
                  child_price: {
                    currency: "EUR",
                    amount: 50,
                  },
                  senior_price: {
                    currency: "EUR",
                    amount: 75,
                  },
                },
                duration_minutes: 120,
                available_times: [
                  {
                    date: "2026-05-05",
                    time: "10:00",
                    available_spots: 10,
                  },
                  {
                    date: "2026-05-06",
                    time: "14:00",
                    available_spots: 8,
                  },
                  {
                    date: "2026-05-07",
                    time: "09:00",
                    available_spots: 12,
                  },
                ],
                highlights: [
                  "Sauna and Turkish bath access",
                  "Relaxation area with tea room",
                  "Professional massage options",
                ],
                included: [
                  "Spa access for 2 hours",
                  "Towel and robe",
                  "Tea and refreshments",
                ],
                excluded: ["Massages (extra fee)", "Food and beverages"],
                min_participants: 1,
                max_participants: 20,
                difficulty_level: "easy",
                hotel_pickup: false,
                meal_included: false,
                cancellation_policy: "Free cancellation up to 24 hours before",
                scores: {
                  price_score: 0.8,
                  quality_score: 0.85,
                  convenience_score: 0.9,
                  preference_score: 0.95,
                },
                booking_url:
                  "https://www.booking.com/hotel/it/ostia-antica-park.en-gb.html",
                provider: "Ostia Antica Park Hotel",
                available: true,
                image_urls: [
                  "https://example.com/otium-spa1.jpg",
                  "https://example.com/otium-spa2.jpg",
                ],
              },
              {
                id: "beach-lido-di-ostia-relax-2",
                name: "Lido di Ostia Private Beach Relaxation Day",
                description:
                  "Enjoy a relaxing day on the golden sands of Lido di Ostia beach with private sunbed, umbrella, and access to showers in the beautiful Presidential Natural Park area.",
                category: 5,
                location: {
                  city: "Lido di Ostia",
                  country: "Italy",
                  airport_code: "FCO",
                  latitude: 41.7172,
                  longitude: 12.2825,
                },
                distance_from_query_km: 8,
                rating: 4.5,
                review_count: 1200,
                price_per_person: {
                  currency: "EUR",
                  amount: 35,
                },
                price_details: {
                  adult_price: {
                    currency: "EUR",
                    amount: 35,
                  },
                  child_price: {
                    currency: "EUR",
                    amount: 20,
                  },
                  senior_price: {
                    currency: "EUR",
                    amount: 30,
                  },
                },
                duration_minutes: 480,
                available_times: [
                  {
                    date: "2026-05-05",
                    time: "09:00",
                    available_spots: 15,
                  },
                  {
                    date: "2026-05-06",
                    time: "10:00",
                    available_spots: 20,
                  },
                  {
                    date: "2026-05-07",
                    time: "11:00",
                    available_spots: 18,
                  },
                ],
                highlights: [
                  "Prime beach location near Capocotta Park",
                  "Clean sands and clear sea",
                  "Daily beach cleaning service",
                ],
                included: [
                  "Sunbed and umbrella",
                  "Showers and changing facilities",
                  "Beach attendant service",
                ],
                excluded: ["Food and drinks", "Additional equipment rental"],
                min_participants: 1,
                max_participants: 10,
                difficulty_level: "easy",
                hotel_pickup: false,
                meal_included: false,
                cancellation_policy: "Free cancellation up to 12 hours before",
                scores: {
                  price_score: 0.95,
                  quality_score: 0.9,
                  convenience_score: 0.85,
                  preference_score: 0.9,
                },
                booking_url: "https://www.ilgabbiano-ostia.it",
                provider: "Il Gabbiano Beach Resort",
                available: true,
                image_urls: [
                  "https://example.com/lido-beach1.jpg",
                  "https://example.com/lido-beach2.jpg",
                ],
              },
              {
                id: "royalroom-spa-unwind-3",
                name: "Royalroom Relaxing Spa & Beach Wellness Session",
                description:
                  "Luxury spa session combined with beach proximity at Royalroom in Lido di Ostia, offering massages, wellness treatments, and relaxation overlooking the Tyrrhenian Sea.",
                category: 9,
                location: {
                  city: "Lido di Ostia",
                  country: "Italy",
                  airport_code: "FCO",
                  latitude: 41.72,
                  longitude: 12.29,
                },
                distance_from_query_km: 7.5,
                rating: 4.6,
                review_count: 250,
                price_per_person: {
                  currency: "EUR",
                  amount: 120,
                },
                price_details: {
                  adult_price: {
                    currency: "EUR",
                    amount: 120,
                  },
                  child_price: {
                    currency: "EUR",
                    amount: 70,
                  },
                  senior_price: {
                    currency: "EUR",
                    amount: 105,
                  },
                },
                duration_minutes: 180,
                available_times: [
                  {
                    date: "2026-05-05",
                    time: "11:00",
                    available_spots: 6,
                  },
                  {
                    date: "2026-05-06",
                    time: "15:00",
                    available_spots: 8,
                  },
                  {
                    date: "2026-05-07",
                    time: "10:30",
                    available_spots: 10,
                  },
                ],
                highlights: [
                  "Signature Italian massages",
                  "Sea-view treatment rooms",
                  "Luxury wellness amenities",
                ],
                included: [
                  "90-minute spa treatment",
                  "Access to relaxation lounge",
                  "Herbal teas",
                ],
                excluded: ["Private beach access", "Meals"],
                min_participants: 1,
                max_participants: 15,
                difficulty_level: "easy",
                hotel_pickup: true,
                meal_included: false,
                cancellation_policy: "Free cancellation up to 48 hours before",
                scores: {
                  price_score: 0.7,
                  quality_score: 0.95,
                  convenience_score: 0.9,
                  preference_score: 0.92,
                },
                booking_url:
                  "https://www.booking.com/hotel/it/royalroom-relaxing-spa-luxury-apartments.en-gb.html",
                provider: "Royalroom Spa",
                available: true,
                image_urls: [
                  "https://example.com/royalroom-spa1.jpg",
                  "https://example.com/royalroom-spa2.jpg",
                ],
              },
            ],
          },
        },
        {
          type: SectionType.STAY,
          data: {
            hotel: {
              id: "d76672c0-31c0-5864-9d51-17a6ced385c2",
              name: "Novotel Salerno Est Arechi",
              description:
                "Prime Location and Modern ComfortsNovotel Salerno Est Arechi offers a prime seafront location near Arechi Stadium. This 4-star modern hotel provides all the comforts you'd expect. Enjoy a summer pool, fitness centre, and an excellent restaurant.Well-Equipped for Leisure and BusinessGuest rooms feature free wired internet, flat-screen TVs with satellite channels, and free Wi-Fi in the business centre. Stay active in the gym, unwind on the sun terrace, or let children enjoy the library and play ar",
              location: {
                city: "Salerno",
                country: "it",
                airport_code: "",
                latitude: 40.649079,
                longitude: 14.816119,
              },
              distance_to_center_km: 2.5,
              image: "https://static.cupid.travel/hotels/492221698.jpg",
              rating: 8,
              review_count: 1853,
              rating_category: "Excellent",
              price_per_night: {
                currency: "USD",
                amount: 127.27999999999999,
              },
              total_price: {
                currency: "USD",
                amount: 381.84,
              },
              additional_fees: [
                {
                  name: "City Tax",
                  amount: {
                    currency: "USD",
                    amount: 28.22,
                  },
                  mandatory: true,
                },
              ],
              room: {
                type: "Superior Double Room",
                beds: 1,
                bed_type: "standard",
                max_occupancy: 2,
                size_sqm: 0,
                features: [],
              },
              amenities: [
                "Facility_2083",
                "Facility_16",
                "Facility_3",
                "Facility_15",
                "Facility_4",
                "Facility_48",
                "Facility_91",
                "Facility_51",
                "Facility_81",
                "Facility_64",
              ],
              category: "upscale",
              star_rating: 4,
              scores: {
                price_score: 0.8282666666666667,
                quality_score: 0.8,
                convenience_score: 0.75,
                preference_score: 0.5,
              },
              booking_url: "https://booking.liteapi.travel/hotels/lp2b4de",
              provider: "nuitee",
              available: true,
            },
            activities: [
              {
                id: "path-of-gods-guided-hike",
                name: "Path of the Gods Guided Hike from Agerola",
                description:
                  "Conquer the legendary Path of the Gods trail with stunning coastal views, dramatic cliffs, terraced vineyards, and historic sites on this moderate guided hike along the Amalfi Coast.",
                category: 1,
                location: {
                  city: "Agerola",
                  country: "IT",
                  airport_code: "NAP",
                  latitude: 40.65,
                  longitude: 14.5333,
                },
                distance_from_query_km: 15.2,
                rating: 4.8,
                review_count: 1250,
                price_per_person: {
                  currency: "EUR",
                  amount: 85,
                },
                price_details: {
                  adult_price: {
                    currency: "EUR",
                    amount: 85,
                  },
                  child_price: {
                    currency: "EUR",
                    amount: 65,
                  },
                  senior_price: {
                    currency: "EUR",
                    amount: 75,
                  },
                },
                duration_minutes: 240,
                available_times: [
                  {
                    date: "2026-05-07",
                    time: "09:00",
                    available_spots: 12,
                  },
                  {
                    date: "2026-05-08",
                    time: "09:00",
                    available_spots: 10,
                  },
                  {
                    date: "2026-05-09",
                    time: "09:00",
                    available_spots: 14,
                  },
                ],
                highlights: [
                  "Breathtaking views over Positano and the sea",
                  "Pass ancient monasteries and farmhouses",
                  "Expert guide shares local history",
                ],
                included: [
                  "Guided tour",
                  "Hiking poles",
                  "Bottled water",
                  "Trail snacks",
                ],
                excluded: [
                  "Lunch",
                  "Transport from Salerno",
                  "Personal expenses",
                ],
                min_participants: 1,
                max_participants: 15,
                difficulty_level: "moderate",
                hotel_pickup: false,
                meal_included: false,
                cancellation_policy: "Free cancellation up to 24 hours before",
                scores: {
                  price_score: 0.85,
                  quality_score: 0.95,
                  convenience_score: 0.8,
                  preference_score: 1,
                },
                booking_url: "https://www.viator.com/tour/path-of-gods",
                provider: "Trekking Amalfi Coast",
                available: true,
                image_urls: [
                  "https://example.com/path-gods1.jpg",
                  "https://example.com/path-gods2.jpg",
                ],
              },
              {
                id: "valle-ferriere-wellness-walk",
                name: "Valle delle Ferriere Nature Walk & Wellness",
                description:
                  "Serene guided walk through the lush Valle delle Ferriere reserve, featuring waterfalls, ancient ruins, fern forests, and a relaxing citrus tasting session for coastal wellness.",
                category: 5,
                location: {
                  city: "Amalfi",
                  country: "IT",
                  airport_code: "NAP",
                  latitude: 40.6333,
                  longitude: 14.6,
                },
                distance_from_query_km: 18.5,
                rating: 4.7,
                review_count: 856,
                price_per_person: {
                  currency: "EUR",
                  amount: 59,
                },
                price_details: {
                  adult_price: {
                    currency: "EUR",
                    amount: 59,
                  },
                  child_price: {
                    currency: "EUR",
                    amount: 45,
                  },
                  senior_price: {
                    currency: "EUR",
                    amount: 55,
                  },
                },
                duration_minutes: 150,
                available_times: [
                  {
                    date: "2026-05-07",
                    time: "10:30",
                    available_spots: 8,
                  },
                  {
                    date: "2026-05-09",
                    time: "10:30",
                    available_spots: 10,
                  },
                  {
                    date: "2026-05-10",
                    time: "10:30",
                    available_spots: 12,
                  },
                ],
                highlights: [
                  "Waterfalls and ruined paper mills",
                  "Fragrant lemon groves",
                  "Limoncello and lemon product tasting",
                ],
                included: [
                  "English-speaking guide",
                  "Lemon tasting experience",
                  "Entrance fees",
                ],
                excluded: ["Meals", "Transport"],
                min_participants: 2,
                max_participants: 12,
                difficulty_level: "easy",
                hotel_pickup: true,
                meal_included: false,
                cancellation_policy: "Free cancellation up to 48 hours before",
                scores: {
                  price_score: 0.9,
                  quality_score: 0.92,
                  convenience_score: 0.88,
                  preference_score: 0.95,
                },
                booking_url: "https://www.viator.com/valle-ferriere",
                provider: "Amalfi Adventures",
                available: true,
                image_urls: [
                  "https://example.com/ferriere1.jpg",
                  "https://example.com/ferriere2.jpg",
                ],
              },
              {
                id: "path-of-lemons-coastal-wellness",
                name: "Sentiero dei Limoni Wellness Walk with Tasting",
                description:
                  "Traverse the fragrant Path of the Lemons between Maiori and Minori, enjoying sea views, lemon terraces, and a farm tasting of limoncello, jams, and salads for a relaxing coastal experience.",
                category: 12,
                location: {
                  city: "Maiori",
                  country: "IT",
                  airport_code: "NAP",
                  latitude: 40.65,
                  longitude: 14.65,
                },
                distance_from_query_km: 12.8,
                rating: 4.6,
                review_count: 342,
                price_per_person: {
                  currency: "EUR",
                  amount: 55,
                },
                price_details: {
                  adult_price: {
                    currency: "EUR",
                    amount: 55,
                  },
                  child_price: {
                    currency: "EUR",
                    amount: 40,
                  },
                  senior_price: {
                    currency: "EUR",
                    amount: 50,
                  },
                },
                duration_minutes: 180,
                available_times: [
                  {
                    date: "2026-05-08",
                    time: "08:30",
                    available_spots: 15,
                  },
                  {
                    date: "2026-05-09",
                    time: "08:30",
                    available_spots: 12,
                  },
                  {
                    date: "2026-05-10",
                    time: "08:30",
                    available_spots: 14,
                  },
                ],
                highlights: [
                  "Lemon grove immersion",
                  "Stunning mountain-to-sea panoramas",
                  "Fresh lemon-based tastings",
                ],
                included: ["Guided walk", "Farm products tasting", "Water"],
                excluded: ["Lunch", "Hotel transfers"],
                min_participants: 1,
                max_participants: 20,
                difficulty_level: "easy",
                hotel_pickup: false,
                meal_included: true,
                cancellation_policy: "Free cancellation up to 24 hours before",
                scores: {
                  price_score: 0.92,
                  quality_score: 0.9,
                  convenience_score: 0.85,
                  preference_score: 0.98,
                },
                booking_url: "https://www.viator.com/path-lemons",
                provider: "Maiori Lemon Tours",
                available: true,
                image_urls: [
                  "https://example.com/lemons1.jpg",
                  "https://example.com/lemons2.jpg",
                ],
              },
            ],
          },
        },
      ],
    },
  },
];

export default mockData;
