import { SectionType, Trip } from '../../../../shared/types'

const mockData: Trip[] = [
	{
		vibe: "Romantic Paris Getaway",
		layout: {
			sections: [
				{
					type: SectionType.TRANSFER,
					data: {
						id: "t_paris_1",
						mode: 2,
						provider: "City Taxi",
						origin: {
							city: "New York",
							country: "USA",
							airport_code: "JFK",
							latitude: 40.6413,
							longitude: -73.7781,
						},
						destination: {
							city: "New York",
							country: "USA",
							airport_code: "JFK",
							latitude: 40.6413,
							longitude: -73.7781,
						},
						distance_km: 18.2,
						departure_time: "2026-02-10T15:30:00Z",
						arrival_time: "2026-02-10T16:05:00Z",
						duration_minutes: 35,
						total_price: { currency: "USD", amount: 62 },
						price_per_person: { currency: "USD", amount: 31 },
						details: {
							ride: {
								vehicle_type: "sedan",
								seats: 4,
								shared: false,
								estimated_wait_minutes: 6,
							},
						},
						scores: {
							price_score: 0.55,
							quality_score: 0.75,
							convenience_score: 0.9,
							preference_score: 0.7,
						},
						booking_url: "https://example.com/book/taxi/jfk",
						available: true,
					},
				},
				{
					type: SectionType.FLIGHT,
					data: {
						id: "f_paris_out",
						outbound: {
							origin: {
								city: "New York",
								country: "USA",
								airport_code: "JFK",
								latitude: 40.6413,
								longitude: -73.7781,
							},
							destination: {
								city: "Paris",
								country: "France",
								airport_code: "CDG",
								latitude: 49.0097,
								longitude: 2.5479,
							},
							departure_time: "2026-02-10T18:30:00Z",
							arrival_time: "2026-02-11T07:45:00Z",
							duration_minutes: 435,
							stops: 0,
							layovers: [],
							airline: "Air France",
							flight_number: "AF007",
							aircraft: "Boeing 777-300ER",
							cabin_class: "economy",
							amenities: {
								wifi: true,
								meal: true,
								entertainment: true,
								power_outlet: true,
								legroom_inches: 32,
							},
							luggage: {
								checked_bags: 1,
								checked_bag_weight_kg: 23,
								carry_on_bags: 1,
								carry_on_weight_kg: 8,
								carry_on_dimensions_cm: "55x35x25",
							},
						},
						total_price: { currency: "USD", amount: 1240 },
						price_per_person: { currency: "USD", amount: 620 },
						scores: {
							price_score: 0.58,
							quality_score: 0.82,
							convenience_score: 0.78,
							preference_score: 0.8,
						},
						booking_url: "https://example.com/book/flight/af007",
						provider: "Air France",
						available: true,
					},
				},
				{
					type: SectionType.TRANSFER,
					data: {
						id: "t_paris_2",
						mode: 3,
						provider: "RideShare",
						origin: {
							city: "Paris",
							country: "France",
							airport_code: "CDG",
							latitude: 49.0097,
							longitude: 2.5479,
						},
						destination: {
							city: "Paris",
							country: "France",
							airport_code: "PAR",
							latitude: 48.8566,
							longitude: 2.3522,
						},
						distance_km: 32.0,
						departure_time: "2026-02-11T09:00:00Z",
						arrival_time: "2026-02-11T09:55:00Z",
						duration_minutes: 55,
						total_price: { currency: "EUR", amount: 58 },
						price_per_person: { currency: "EUR", amount: 29 },
						details: {
							ride: {
								vehicle_type: "suv",
								seats: 4,
								shared: false,
								estimated_wait_minutes: 8,
							},
						},
						scores: {
							price_score: 0.6,
							quality_score: 0.75,
							convenience_score: 0.85,
							preference_score: 0.75,
						},
						booking_url: "https://example.com/book/rideshare/paris",
						available: true,
					},
				},
				{
					type: SectionType.STAY,
					data: {
						hotel: {
							id: "h_paris_1",
							name: "Hôtel Lumière",
							description: "Boutique hotel near the Seine with a cozy romantic vibe.",
							location: {
								city: "Paris",
								country: "France",
								airport_code: "PAR",
								latitude: 48.8566,
								longitude: 2.3522,
							},
							distance_to_center_km: 1.2,
							image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=60",
							rating: 4.6,
							review_count: 1842,
							rating_category: "Excellent",
							price_per_night: { currency: "EUR", amount: 220 },
							total_price: { currency: "EUR", amount: 880 },
							additional_fees: [
								{
									name: "City tax",
									amount: { currency: "EUR", amount: 24 },
									mandatory: true,
								},
							],
							room: {
								type: "deluxe",
								beds: 1,
								bed_type: "queen",
								max_occupancy: 2,
								size_sqm: 26,
								features: ["balcony", "espresso machine", "rain shower"],
							},
							amenities: ["wifi", "breakfast", "concierge"],
							category: "boutique",
							star_rating: 4,
							scores: {
								price_score: 0.55,
								quality_score: 0.88,
								convenience_score: 0.9,
								preference_score: 0.92,
							},
							booking_url: "https://example.com/book/hotel/lumiere",
							provider: "ExampleHotels",
							available: true,
						},
						activities: [
							{
								id: "a_paris_1",
								name: "Seine Dinner Cruise",
								description: "Evening cruise with a multi-course meal and city views.",
								category: 1,
								location: {
									city: "Paris",
									country: "France",
									airport_code: "PAR",
									latitude: 48.8584,
									longitude: 2.2945,
								},
								distance_from_query_km: 2.4,
								rating: 4.7,
								review_count: 5231,
								price_per_person: { currency: "EUR", amount: 95 },
								price_details: {
									adult_price: { currency: "EUR", amount: 95 },
									child_price: { currency: "EUR", amount: 55 },
									senior_price: { currency: "EUR", amount: 85 },
								},
								duration_minutes: 150,
								available_times: [
									{ date: "2026-02-12", time: "19:30", available_spots: 18 },
									{ date: "2026-02-13", time: "19:30", available_spots: 12 },
								],
								highlights: ["Eiffel Tower views", "Live music"],
								included: ["Dinner", "Cruise"],
								excluded: ["Hotel pickup"],
								min_participants: 1,
								max_participants: 120,
								difficulty_level: "easy",
								hotel_pickup: false,
								meal_included: true,
								cancellation_policy: "Free cancellation up to 24 hours before.",
								scores: {
									price_score: 0.6,
									quality_score: 0.9,
									convenience_score: 0.8,
									preference_score: 0.95,
								},
								booking_url: "https://example.com/book/activity/seine-cruise",
								provider: "ParisExperiences",
								available: true,
								image_urls: [
									"https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=60",
									"https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?auto=format&fit=crop&w=1200&q=60",
								],
							},
							{
								id: "a_paris_2",
								name: "Louvre Museum Timed Entry",
								description: "Skip the line with a reserved time slot.",
								category: 2,
								location: {
									city: "Paris",
									country: "France",
									airport_code: "PAR",
									latitude: 48.8606,
									longitude: 2.3376,
								},
								distance_from_query_km: 1.1,
								rating: 4.5,
								review_count: 28451,
								price_per_person: { currency: "EUR", amount: 22 },
								price_details: {
									adult_price: { currency: "EUR", amount: 22 },
									child_price: { currency: "EUR", amount: 0 },
									senior_price: { currency: "EUR", amount: 22 },
								},
								duration_minutes: 180,
								available_times: [
									{ date: "2026-02-12", time: "10:30", available_spots: 70 },
									{ date: "2026-02-13", time: "14:00", available_spots: 45 },
								],
								highlights: ["Mona Lisa", "Classic sculptures"],
								included: ["Timed entry ticket"],
								excluded: ["Guided tour"],
								min_participants: 1,
								max_participants: 250,
								difficulty_level: "easy",
								hotel_pickup: false,
								meal_included: false,
								cancellation_policy: "Non-refundable.",
								scores: {
									price_score: 0.9,
									quality_score: 0.86,
									convenience_score: 0.75,
									preference_score: 0.88,
								},
								booking_url: "https://example.com/book/activity/louvre",
								provider: "MuseumPass",
								available: true,
								image_urls: [
									"https://images.unsplash.com/photo-1565099825058-3b5f6b7bd8b0?auto=format&fit=crop&w=1200&q=60",
								],
							},
						],
					},
				},
				{
					type: SectionType.TRANSFER,
					data: {
						id: "t_paris_return",
						mode: 2,
						provider: "City Taxi",
						origin: {
							city: "Paris",
							country: "France",
							airport_code: "PAR",
							latitude: 48.8566,
							longitude: 2.3522,
						},
						destination: {
							city: "Paris",
							country: "France",
							airport_code: "CDG",
							latitude: 49.0097,
							longitude: 2.5479,
						},
						distance_km: 32.0,
						departure_time: "2026-02-14T11:00:00Z",
						arrival_time: "2026-02-14T12:00:00Z",
						duration_minutes: 60,
						total_price: { currency: "EUR", amount: 55 },
						price_per_person: { currency: "EUR", amount: 27.5 },
						details: {
							ride: {
								vehicle_type: "sedan",
								seats: 4,
								shared: false,
								estimated_wait_minutes: 5,
							},
						},
						scores: {
							price_score: 0.6,
							quality_score: 0.75,
							convenience_score: 0.85,
							preference_score: 0.75,
						},
						booking_url: "https://example.com/book/taxi/paris-cdg",
						available: true,
					},
				},
				{
					type: SectionType.FLIGHT,
					data: {
						id: "f_paris_return",
						outbound: {
							origin: {
								city: "Paris",
								country: "France",
								airport_code: "CDG",
								latitude: 49.0097,
								longitude: 2.5479,
							},
							destination: {
								city: "New York",
								country: "USA",
								airport_code: "JFK",
								latitude: 40.6413,
								longitude: -73.7781,
							},
							departure_time: "2026-02-14T14:20:00Z",
							arrival_time: "2026-02-14T22:10:00Z",
							duration_minutes: 470,
							stops: 0,
							layovers: [],
							airline: "Air France",
							flight_number: "AF006",
							aircraft: "Boeing 777-300ER",
							cabin_class: "economy",
							amenities: {
								wifi: true,
								meal: true,
								entertainment: true,
								power_outlet: true,
								legroom_inches: 32,
							},
							luggage: {
								checked_bags: 1,
								checked_bag_weight_kg: 23,
								carry_on_bags: 1,
								carry_on_weight_kg: 8,
								carry_on_dimensions_cm: "55x35x25",
							},
						},
						total_price: { currency: "USD", amount: 1220 },
						price_per_person: { currency: "USD", amount: 610 },
						scores: {
							price_score: 0.6,
							quality_score: 0.82,
							convenience_score: 0.78,
							preference_score: 0.8,
						},
						booking_url: "https://example.com/book/flight/af006",
						provider: "Air France",
						available: true,
					},
				},
			],
		},
	},

	{
		vibe: "Family Tokyo Adventure",
		layout: {
			sections: [
				{
					type: SectionType.TRANSFER,
					data: {
						id: "t_tokyo_1",
						mode: 3,
						provider: "RideShare",
						origin: {
							city: "Los Angeles",
							country: "USA",
							airport_code: "LAX",
							latitude: 33.9416,
							longitude: -118.4085,
						},
						destination: {
							city: "Los Angeles",
							country: "USA",
							airport_code: "LAX",
							latitude: 33.9416,
							longitude: -118.4085,
						},
						distance_km: 22.5,
						departure_time: "2026-03-05T16:00:00Z",
						arrival_time: "2026-03-05T16:45:00Z",
						duration_minutes: 45,
						total_price: { currency: "USD", amount: 54 },
						price_per_person: { currency: "USD", amount: 13.5 },
						details: {
							ride: {
								vehicle_type: "van",
								seats: 6,
								shared: false,
								estimated_wait_minutes: 7,
							},
						},
						scores: {
							price_score: 0.7,
							quality_score: 0.78,
							convenience_score: 0.88,
							preference_score: 0.8,
						},
						booking_url: "https://example.com/book/rideshare/lax",
						available: true,
					},
				},
				{
					type: SectionType.FLIGHT,
					data: {
						id: "f_tokyo_out",
						outbound: {
							origin: {
								city: "Los Angeles",
								country: "USA",
								airport_code: "LAX",
								latitude: 33.9416,
								longitude: -118.4085,
							},
							destination: {
								city: "Tokyo",
								country: "Japan",
								airport_code: "HND",
								latitude: 35.5494,
								longitude: 139.7798,
							},
							departure_time: "2026-03-05T19:30:00Z",
							arrival_time: "2026-03-06T10:35:00Z",
							duration_minutes: 785,
							stops: 0,
							layovers: [],
							airline: "Japan Airlines",
							flight_number: "JL061",
							aircraft: "Boeing 787-9",
							cabin_class: "economy",
							amenities: {
								wifi: true,
								meal: true,
								entertainment: true,
								power_outlet: true,
								legroom_inches: 33,
							},
							luggage: {
								checked_bags: 1,
								checked_bag_weight_kg: 23,
								carry_on_bags: 1,
								carry_on_weight_kg: 10,
								carry_on_dimensions_cm: "55x40x25",
							},
						},
						total_price: { currency: "USD", amount: 3180 },
						price_per_person: { currency: "USD", amount: 795 },
						scores: {
							price_score: 0.45,
							quality_score: 0.9,
							convenience_score: 0.8,
							preference_score: 0.85,
						},
						booking_url: "https://example.com/book/flight/jl061",
						provider: "Japan Airlines",
						available: true,
					},
				},
				{
					type: SectionType.STAY,
					data: {
						hotel: {
							id: "h_tokyo_1",
							name: "Tokyo Family Suites",
							description: "Spacious rooms near Shinjuku with easy transit access.",
							location: {
								city: "Tokyo",
								country: "Japan",
								airport_code: "TYO",
								latitude: 35.6895,
								longitude: 139.6917,
							},
							distance_to_center_km: 0.9,
							image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=60",
							rating: 4.4,
							review_count: 932,
							rating_category: "Very Good",
							price_per_night: { currency: "USD", amount: 160 },
							total_price: { currency: "USD", amount: 800 },
							additional_fees: [],
							room: {
								type: "family suite",
								beds: 3,
								bed_type: "twin + sofa",
								max_occupancy: 4,
								size_sqm: 42,
								features: ["kitchenette", "washer", "city view"],
							},
							amenities: ["wifi", "laundry", "breakfast"],
							category: "midscale",
							star_rating: 4,
							scores: {
								price_score: 0.65,
								quality_score: 0.82,
								convenience_score: 0.92,
								preference_score: 0.86,
							},
							booking_url: "https://example.com/book/hotel/tokyo-family-suites",
							provider: "ExampleHotels",
							available: true,
						},
						activities: [
							{
								id: "a_tokyo_1",
								name: "TeamLab Planets",
								description: "Immersive digital art museum experience.",
								category: 2,
								location: {
									city: "Tokyo",
									country: "Japan",
									airport_code: "TYO",
									latitude: 35.6272,
									longitude: 139.7766,
								},
								distance_from_query_km: 5.1,
								rating: 4.7,
								review_count: 18412,
								price_per_person: { currency: "USD", amount: 25 },
								price_details: {
									adult_price: { currency: "USD", amount: 25 },
									child_price: { currency: "USD", amount: 13 },
									senior_price: { currency: "USD", amount: 21 },
								},
								duration_minutes: 120,
								available_times: [
									{ date: "2026-03-07", time: "11:00", available_spots: 60 },
									{ date: "2026-03-08", time: "15:00", available_spots: 40 },
								],
								highlights: ["Interactive rooms", "Family-friendly"],
								included: ["Entry ticket"],
								excluded: ["Transportation"],
								min_participants: 1,
								max_participants: 200,
								difficulty_level: "easy",
								hotel_pickup: false,
								meal_included: false,
								cancellation_policy: "Non-refundable.",
								scores: {
									price_score: 0.7,
									quality_score: 0.92,
									convenience_score: 0.7,
									preference_score: 0.88,
								},
								booking_url: "https://example.com/book/activity/teamlab",
								provider: "TokyoTickets",
								available: true,
								image_urls: [
									"https://images.unsplash.com/photo-1516541196182-6bdb0516ed27?auto=format&fit=crop&w=1200&q=60",
								],
							},
							{
								id: "a_tokyo_2",
								name: "Asakusa Food Walk",
								description: "Guided street food tasting near Senso-ji.",
								category: 12,
								location: {
									city: "Tokyo",
									country: "Japan",
									airport_code: "TYO",
									latitude: 35.7148,
									longitude: 139.7967,
								},
								distance_from_query_km: 4.2,
								rating: 4.6,
								review_count: 2780,
								price_per_person: { currency: "USD", amount: 43 },
								price_details: {
									adult_price: { currency: "USD", amount: 43 },
									child_price: { currency: "USD", amount: 30 },
									senior_price: { currency: "USD", amount: 40 },
								},
								duration_minutes: 150,
								available_times: [
									{ date: "2026-03-07", time: "13:00", available_spots: 16 },
								],
								highlights: ["Local snacks", "Temple district"],
								included: ["Food tastings"],
								excluded: ["Extra purchases"],
								min_participants: 2,
								max_participants: 12,
								difficulty_level: "easy",
								hotel_pickup: false,
								meal_included: true,
								cancellation_policy: "Free cancellation up to 48 hours before.",
								scores: {
									price_score: 0.65,
									quality_score: 0.88,
									convenience_score: 0.75,
									preference_score: 0.84,
								},
								booking_url: "https://example.com/book/activity/asakusa-food",
								provider: "TokyoEats",
								available: true,
								image_urls: [
									"https://images.unsplash.com/photo-1526481280695-3c687fd5432c?auto=format&fit=crop&w=1200&q=60",
								],
							},
						],
					},
				},
				{
					type: SectionType.TRANSFER,
					data: {
						id: "t_tokyo_hakone",
						mode: 1,
						provider: "Odakyu Romance Car",
						origin: {
							city: "Tokyo",
							country: "Japan",
							airport_code: "TYO",
							latitude: 35.6895,
							longitude: 139.6917,
						},
						destination: {
							city: "Hakone",
							country: "Japan",
							airport_code: "TYO",
							latitude: 35.2326,
							longitude: 139.1069,
						},
						distance_km: 85.0,
						departure_time: "2026-03-08T09:00:00Z",
						arrival_time: "2026-03-08T10:25:00Z",
						duration_minutes: 85,
						total_price: { currency: "USD", amount: 50 },
						price_per_person: { currency: "USD", amount: 12.5 },
						details: {
							transit: {
								line: "Romance Car",
								stops: 3,
								transfer_points: ["Shinjuku", "Odawara", "Hakone-Yumoto"],
								service_class: "reserved",
								wifi: true,
								food_service: true,
							},
						},
						scores: {
							price_score: 0.75,
							quality_score: 0.9,
							convenience_score: 0.85,
							preference_score: 0.88,
						},
						booking_url: "https://example.com/book/odakyu/romance-car",
						available: true,
					},
				},
				{
					type: SectionType.STAY,
					data: {
						hotel: {
							id: "h_hakone_1",
							name: "Hakone Ryokan Setsugetsuka",
							description: "Traditional Japanese inn with private onsen and mountain views.",
							location: {
								city: "Hakone",
								country: "Japan",
								airport_code: "TYO",
								latitude: 35.2326,
								longitude: 139.1069,
							},
							distance_to_center_km: 2.5,
							image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=60",
							rating: 4.8,
							review_count: 456,
							rating_category: "Exceptional",
							price_per_night: { currency: "USD", amount: 280 },
							total_price: { currency: "USD", amount: 280 },
							additional_fees: [
								{
									name: "Hot spring tax",
									amount: { currency: "USD", amount: 3 },
									mandatory: true,
								},
							],
							room: {
								type: "tatami suite",
								beds: 2,
								bed_type: "futon",
								max_occupancy: 4,
								size_sqm: 38,
								features: ["private onsen", "garden view", "yukata provided"],
							},
							amenities: ["wifi", "onsen", "breakfast", "dinner"],
							category: "ryokan",
							star_rating: 4,
							scores: {
								price_score: 0.5,
								quality_score: 0.95,
								convenience_score: 0.7,
								preference_score: 0.92,
							},
							booking_url: "https://example.com/book/hotel/hakone-ryokan",
							provider: "JapanStay",
							available: true,
						},
						activities: [
							{
								id: "a_hakone_1",
								name: "Lake Ashi Pirate Ship Cruise",
								description: "Scenic cruise with views of Mt. Fuji on clear days.",
								category: 5,
								location: {
									city: "Hakone",
									country: "Japan",
									airport_code: "TYO",
									latitude: 35.2048,
									longitude: 139.0263,
								},
								distance_from_query_km: 4.8,
								rating: 4.5,
								review_count: 3240,
								price_per_person: { currency: "USD", amount: 12 },
								price_details: {
									adult_price: { currency: "USD", amount: 12 },
									child_price: { currency: "USD", amount: 6 },
									senior_price: { currency: "USD", amount: 10 },
								},
								duration_minutes: 40,
								available_times: [
									{ date: "2026-03-08", time: "11:00", available_spots: 200 },
									{ date: "2026-03-08", time: "14:00", available_spots: 180 },
								],
								highlights: ["Mt. Fuji views", "Unique ship design"],
								included: ["Round trip cruise"],
								excluded: ["Meals"],
								min_participants: 1,
								max_participants: 500,
								difficulty_level: "easy",
								hotel_pickup: false,
								meal_included: false,
								cancellation_policy: "Free cancellation up to 24 hours before.",
								scores: {
									price_score: 0.9,
									quality_score: 0.8,
									convenience_score: 0.75,
									preference_score: 0.82,
								},
								booking_url: "https://example.com/book/activity/ashi-cruise",
								provider: "HakoneTours",
								available: true,
								image_urls: [
									"https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?auto=format&fit=crop&w=1200&q=60",
								],
							},
						],
					},
				},
				{
					type: SectionType.TRANSFER,
					data: {
						id: "t_hakone_tokyo",
						mode: 1,
						provider: "Odakyu Romance Car",
						origin: {
							city: "Hakone",
							country: "Japan",
							airport_code: "TYO",
							latitude: 35.2326,
							longitude: 139.1069,
						},
						destination: {
							city: "Tokyo",
							country: "Japan",
							airport_code: "TYO",
							latitude: 35.6895,
							longitude: 139.6917,
						},
						distance_km: 85.0,
						departure_time: "2026-03-09T16:00:00Z",
						arrival_time: "2026-03-09T17:25:00Z",
						duration_minutes: 85,
						total_price: { currency: "USD", amount: 50 },
						price_per_person: { currency: "USD", amount: 12.5 },
						details: {
							transit: {
								line: "Romance Car",
								stops: 3,
								transfer_points: ["Hakone-Yumoto", "Odawara", "Shinjuku"],
								service_class: "reserved",
								wifi: true,
								food_service: true,
							},
						},
						scores: {
							price_score: 0.75,
							quality_score: 0.9,
							convenience_score: 0.85,
							preference_score: 0.88,
						},
						booking_url: "https://example.com/book/odakyu/romance-car",
						available: true,
					},
				},
				{
					type: SectionType.TRANSFER,
					data: {
						id: "t_tokyo_return",
						mode: 4,
						provider: "Tokyo Taxi",
						origin: {
							city: "Tokyo",
							country: "Japan",
							airport_code: "TYO",
							latitude: 35.6895,
							longitude: 139.6917,
						},
						destination: {
							city: "Tokyo",
							country: "Japan",
							airport_code: "HND",
							latitude: 35.5494,
							longitude: 139.7798,
						},
						distance_km: 18.0,
						departure_time: "2026-03-09T22:30:00Z",
						arrival_time: "2026-03-09T23:15:00Z",
						duration_minutes: 45,
						total_price: { currency: "USD", amount: 65 },
						price_per_person: { currency: "USD", amount: 16.25 },
						details: {
							ride: {
								vehicle_type: "sedan",
								seats: 4,
								shared: false,
								estimated_wait_minutes: 5,
							},
						},
						scores: {
							price_score: 0.65,
							quality_score: 0.8,
							convenience_score: 0.85,
							preference_score: 0.78,
						},
						booking_url: "https://example.com/book/taxi/tokyo-hnd",
						available: true,
					},
				},
				{
					type: SectionType.FLIGHT,
					data: {
						id: "f_tokyo_return",
						outbound: {
							origin: {
								city: "Tokyo",
								country: "Japan",
								airport_code: "HND",
								latitude: 35.5494,
								longitude: 139.7798,
							},
							destination: {
								city: "Los Angeles",
								country: "USA",
								airport_code: "LAX",
								latitude: 33.9416,
								longitude: -118.4085,
							},
							departure_time: "2026-03-10T02:00:00Z",
							arrival_time: "2026-03-10T13:30:00Z",
							duration_minutes: 690,
							stops: 0,
							layovers: [],
							airline: "Japan Airlines",
							flight_number: "JL062",
							aircraft: "Boeing 787-9",
							cabin_class: "economy",
							amenities: {
								wifi: true,
								meal: true,
								entertainment: true,
								power_outlet: true,
								legroom_inches: 33,
							},
							luggage: {
								checked_bags: 1,
								checked_bag_weight_kg: 23,
								carry_on_bags: 1,
								carry_on_weight_kg: 10,
								carry_on_dimensions_cm: "55x40x25",
							},
						},
						total_price: { currency: "USD", amount: 3120 },
						price_per_person: { currency: "USD", amount: 780 },
						scores: {
							price_score: 0.48,
							quality_score: 0.9,
							convenience_score: 0.8,
							preference_score: 0.85,
						},
						booking_url: "https://example.com/book/flight/jl062",
						provider: "Japan Airlines",
						available: true,
					},
				},
			],
		},
	},

	{
		vibe: "Budget Barcelona Explorer",
		layout: {
			sections: [
				{
					type: SectionType.FLIGHT,
					data: {
						id: "f_bcn_out",
						outbound: {
							origin: {
								city: "London",
								country: "UK",
								airport_code: "LHR",
								latitude: 51.47,
								longitude: -0.4543,
							},
							destination: {
								city: "Barcelona",
								country: "Spain",
								airport_code: "BCN",
								latitude: 41.2974,
								longitude: 2.0833,
							},
							departure_time: "2026-04-02T07:10:00Z",
							arrival_time: "2026-04-02T09:25:00Z",
							duration_minutes: 135,
							stops: 0,
							layovers: [],
							airline: "Vueling",
							flight_number: "VY7821",
							aircraft: "Airbus A320",
							cabin_class: "economy",
							amenities: {
								wifi: false,
								meal: false,
								entertainment: false,
								power_outlet: false,
								legroom_inches: 30,
							},
							luggage: {
								checked_bags: 0,
								checked_bag_weight_kg: 0,
								carry_on_bags: 1,
								carry_on_weight_kg: 8,
								carry_on_dimensions_cm: "55x40x20",
							},
						},
						total_price: { currency: "EUR", amount: 180 },
						price_per_person: { currency: "EUR", amount: 90 },
						scores: {
							price_score: 0.9,
							quality_score: 0.6,
							convenience_score: 0.82,
							preference_score: 0.75,
						},
						booking_url: "https://example.com/book/flight/vy7821",
						provider: "Vueling",
						available: true,
					},
				},
				{
					type: SectionType.TRANSFER,
					data: {
						id: "t_bcn_arrival",
						mode: 1,
						provider: "TMB Metro",
						origin: {
							city: "Barcelona",
							country: "Spain",
							airport_code: "BCN",
							latitude: 41.2974,
							longitude: 2.0833,
						},
						destination: {
							city: "Barcelona",
							country: "Spain",
							airport_code: "BCN",
							latitude: 41.3851,
							longitude: 2.1734,
						},
						distance_km: 14.0,
						departure_time: "2026-04-02T10:00:00Z",
						arrival_time: "2026-04-02T10:40:00Z",
						duration_minutes: 40,
						total_price: { currency: "EUR", amount: 5.6 },
						price_per_person: { currency: "EUR", amount: 2.8 },
						details: {
							transit: {
								line: "L9 Sud",
								stops: 8,
								transfer_points: ["Aeroport T1", "Zona Universitària"],
								service_class: "standard",
								wifi: false,
								food_service: false,
							},
						},
						scores: {
							price_score: 0.98,
							quality_score: 0.65,
							convenience_score: 0.8,
							preference_score: 0.78,
						},
						booking_url: "https://example.com/book/metro/bcn",
						available: true,
					},
				},
				{
					type: SectionType.STAY,
					data: {
						hotel: {
							id: "h_bcn_1",
							name: "Barcelona Central Budget",
							description: "Simple, clean stay close to public transit.",
							location: {
								city: "Barcelona",
								country: "Spain",
								airport_code: "BCN",
								latitude: 41.3851,
								longitude: 2.1734,
							},
							distance_to_center_km: 1.8,
							image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=60",
							rating: 4.1,
							review_count: 640,
							rating_category: "Very Good",
							price_per_night: { currency: "EUR", amount: 85 },
							total_price: { currency: "EUR", amount: 255 },
							additional_fees: [],
							room: {
								type: "standard",
								beds: 2,
								bed_type: "twin",
								max_occupancy: 2,
								size_sqm: 18,
								features: ["air conditioning", "workspace"],
							},
							amenities: ["wifi", "24h reception"],
							category: "budget",
							star_rating: 3,
							scores: {
								price_score: 0.92,
								quality_score: 0.68,
								convenience_score: 0.85,
								preference_score: 0.8,
							},
							booking_url: "https://example.com/book/hotel/bcn-central",
							provider: "ExampleHotels",
							available: true,
						},
						activities: [
							{
								id: "a_bcn_1",
								name: "Sagrada Família Guided Tour",
								description: "Fast-track entry with a local guide.",
								category: 1,
								location: {
									city: "Barcelona",
									country: "Spain",
									airport_code: "BCN",
									latitude: 41.4036,
									longitude: 2.1744,
								},
								distance_from_query_km: 2.9,
								rating: 4.8,
								review_count: 11240,
								price_per_person: { currency: "EUR", amount: 39 },
								price_details: {
									adult_price: { currency: "EUR", amount: 39 },
									child_price: { currency: "EUR", amount: 20 },
									senior_price: { currency: "EUR", amount: 35 },
								},
								duration_minutes: 90,
								available_times: [
									{ date: "2026-04-03", time: "10:00", available_spots: 25 },
									{ date: "2026-04-04", time: "12:30", available_spots: 18 },
								],
								highlights: ["Gaudí architecture", "Tower views"],
								included: ["Entry", "Guide"],
								excluded: ["Hotel pickup"],
								min_participants: 1,
								max_participants: 20,
								difficulty_level: "easy",
								hotel_pickup: false,
								meal_included: false,
								cancellation_policy: "Free cancellation up to 24 hours before.",
								scores: {
									price_score: 0.8,
									quality_score: 0.9,
									convenience_score: 0.75,
									preference_score: 0.82,
								},
								booking_url: "https://example.com/book/activity/sagrada",
								provider: "BCN Tours",
								available: true,
								image_urls: [
									"https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?auto=format&fit=crop&w=1200&q=60",
								],
							},
							{
								id: "a_bcn_2",
								name: "Park Güell Sunset Walk",
								description: "Self-paced visit with suggested route and viewpoints.",
								category: 5,
								location: {
									city: "Barcelona",
									country: "Spain",
									airport_code: "BCN",
									latitude: 41.4145,
									longitude: 2.1527,
								},
								distance_from_query_km: 3.8,
								rating: 4.6,
								review_count: 20410,
								price_per_person: { currency: "EUR", amount: 12 },
								price_details: {
									adult_price: { currency: "EUR", amount: 12 },
									child_price: { currency: "EUR", amount: 0 },
									senior_price: { currency: "EUR", amount: 10 },
								},
								duration_minutes: 120,
								available_times: [
									{ date: "2026-04-03", time: "18:30", available_spots: 80 },
								],
								highlights: ["City panoramas", "Colorful mosaics"],
								included: ["Entry"],
								excluded: ["Guide"],
								min_participants: 1,
								max_participants: 400,
								difficulty_level: "easy",
								hotel_pickup: false,
								meal_included: false,
								cancellation_policy: "Non-refundable.",
								scores: {
									price_score: 0.95,
									quality_score: 0.85,
									convenience_score: 0.7,
									preference_score: 0.78,
								},
								booking_url: "https://example.com/book/activity/park-guell",
								provider: "CityPass",
								available: true,
								image_urls: [
									"https://images.unsplash.com/photo-1505731132043-10b3f054f4f7?auto=format&fit=crop&w=1200&q=60",
								],
							},
						],
					},
				},
				{
					type: SectionType.TRANSFER,
					data: {
						id: "t_bcn_return",
						mode: 1,
						provider: "Aerobus",
						origin: {
							city: "Barcelona",
							country: "Spain",
							airport_code: "BCN",
							latitude: 41.3851,
							longitude: 2.1734,
						},
						destination: {
							city: "Barcelona",
							country: "Spain",
							airport_code: "BCN",
							latitude: 41.2974,
							longitude: 2.0833,
						},
						distance_km: 15.0,
						departure_time: "2026-04-05T15:30:00Z",
						arrival_time: "2026-04-05T16:15:00Z",
						duration_minutes: 45,
						total_price: { currency: "EUR", amount: 14 },
						price_per_person: { currency: "EUR", amount: 7 },
						details: {
							transit: {
								line: "Aerobus A1",
								stops: 2,
								transfer_points: ["Plaça Catalunya", "Terminal 1"],
								service_class: "standard",
								wifi: true,
								food_service: false,
							},
						},
						scores: {
							price_score: 0.95,
							quality_score: 0.7,
							convenience_score: 0.85,
							preference_score: 0.82,
						},
						booking_url: "https://example.com/book/aerobus/bcn",
						available: true,
					},
				},
				{
					type: SectionType.FLIGHT,
					data: {
						id: "f_bcn_return",
						outbound: {
							origin: {
								city: "Barcelona",
								country: "Spain",
								airport_code: "BCN",
								latitude: 41.2974,
								longitude: 2.0833,
							},
							destination: {
								city: "London",
								country: "UK",
								airport_code: "LHR",
								latitude: 51.47,
								longitude: -0.4543,
							},
							departure_time: "2026-04-05T18:10:00Z",
							arrival_time: "2026-04-05T20:25:00Z",
							duration_minutes: 135,
							stops: 0,
							layovers: [],
							airline: "Vueling",
							flight_number: "VY7822",
							aircraft: "Airbus A320",
							cabin_class: "economy",
							amenities: {
								wifi: false,
								meal: false,
								entertainment: false,
								power_outlet: false,
								legroom_inches: 30,
							},
							luggage: {
								checked_bags: 0,
								checked_bag_weight_kg: 0,
								carry_on_bags: 1,
								carry_on_weight_kg: 8,
								carry_on_dimensions_cm: "55x40x20",
							},
						},
						total_price: { currency: "EUR", amount: 170 },
						price_per_person: { currency: "EUR", amount: 85 },
						scores: {
							price_score: 0.92,
							quality_score: 0.6,
							convenience_score: 0.82,
							preference_score: 0.75,
						},
						booking_url: "https://example.com/book/flight/vy7822",
						provider: "Vueling",
						available: true,
					},
				},
			],
		},
	},
];

export default mockData;